### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Buni55** [porscheofficial/porscheofficial.github.io#16]
![image](https://github.com/porscheofficial/porscheofficial.github.io/assets/89357573/4aa70b28-7c8b-4deb-acf9-02e7977c2fdd)

The twitter image seems to be broken.

**Comment by itrich** [comment]
Hi @Buni55!

It seems that your operating system doesn't support symbolic links created by `git`. Can you please copy `opengraph-image.jpg` and save it as `twitter-image.jpg`? This should temporary fix the compile error.

You can enable symbolic links in Windows by following this guide: https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201

Best wishes,

Eduard
